auction_site/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.base import reverse
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/auction/')),
    path('admin/', admin.site.urls),
    path('auction/', include('auction.urls')),
    path('accounts/', include('users.urls')),
    # path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auction_site/auction/urls.py
from django.urls import path
from .views import AuctionListView, AuctionCreateView, AuctionDetailsView, bid_raise

app_name = 'auction'

urlpatterns = [
    path('', AuctionListView.as_view(), name='auction-list'),
    path('add/', AuctionCreateView.as_view(), name='auction-create'),
    path('<int:pk>', AuctionDetailsView.as_view(), name='auction-details'),
    path('bid-raise/<int:auction_id>', bid_raise, name='raise-bid'),
]

auction_site/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from users.forms import LoginForm

from .views import SignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(
        template_name="login.html",
        authentication_form=LoginForm
    ), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
]

auction_site/auction/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

User = get_user_model()

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=6, decimal_places=2)


    def __str__(self) -> str:
        return "email=" + self.user.email


# class Product(models.Model):
#     # user = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
#     title = models.CharField(max_length=255)
#     image = models.ImageField(upload_to='images/')
#     description = models.CharField(max_length=500)
#     quantity = models.IntegerField()
#     date_posted = models.DateTimeField(auto_now_add=True, blank=True)
#     #!todo category

#     def __str__(self) -> str:
#         return "user:" + self.user + "title:" + self.title


class Auction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='auctions')
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='images/')
    min_bid = models.DecimalField(max_digits=6, decimal_places=2)
    date_posted = models.DateTimeField(auto_now_add=True, blank=True)
    number_of_bids = models.IntegerField(default=0)
    time_starting = models.DateTimeField(auto_now_add=True, blank=True)
    time_ending = models.DateTimeField()

    def __str__(self) -> str:
        return "user_id: " + str(self.user) + "title: " + str(self.title)

    @property
    def not_expired(self):
        return timezone.now() < self.time_ending


class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bids')
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='bids')
    bid_time = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return "USER_ID:" + str(self.user.id) + " AUCTION_ID:" + \
			str(self.auction.id) + " " + str(self.bid_time)

auction_site/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

auction_site/auction/forms.py
from django import forms
from .models import Auction

class AuctionForm(forms.ModelForm):
    class Meta:
        model = Auction
        fields = '__all__'
        exclude = ['number_of_bids', 'user', 'time_ending']

    def get_total_bids(self):
        return 1

auction_site/users/forms.py
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email',)


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

auction_site/auction/views.py
from datetime import datetime, timedelta

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.views import generic

from .forms import AuctionForm
from .models import Auction, Bid


class AuctionListView(LoginRequiredMixin, generic.ListView):
    model = Auction
    paginate_by = 10
    template_name='auction/auction.html'
    # login_url = 'accounts/login'

    def get_context_data(self, **kwargs):
        print(dir(self))
        context = super().get_context_data(**kwargs)
        context['request'] = self.request
        return context


class AuctionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Auction
    template_name = 'auction/auction_form.html'
    form_class = AuctionForm
    success_url = reverse_lazy('auction:auction-list')

    def form_valid(self, form: AuctionForm) -> HttpResponse:
        user = get_user_model().objects.get(id=self.request.user.id)
        form.instance.user = user
        form.instance.time_ending = datetime.now()+timedelta(days=5)
        return super(AuctionCreateView, self).form_valid(form)


class AuctionDetailsView(generic.DetailView):
    model = Auction


def bid_raise(request, auction_id):
    user = get_user_model().objects.get(id=request.user.id)

    auction = Auction.objects.get(id=auction_id)
    min_bid = auction.min_bid
    # raise by 1/10th for every time a bid is place
    raised_bid = min_bid + (min_bid / 10)
    auction.min_bid = raised_bid
    auction.save()
    Bid.objects.create(auction=auction, user=user)
    messages.success(request, "Bid has been added succesfully")
    return redirect(reverse('auction:auction-list'))

auction_site/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth import views as auth_views
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.urls.base import reverse
from django.views.generic.edit import CreateView
from .forms import CustomUserCreationForm

User = get_user_model()


class SignUpView(SuccessMessageMixin, CreateView):
    """Registers a new user
    """
    model = User
    template_name = 'signup.html'
    form_class = CustomUserCreationForm
    success_message = "You have been registered succesfully"

    def get_success_url(self) -> str:
        return reverse('users:login')


class LoginView(auth_views.LoginView):
    """Logs in a new user using django's default loginview

    Args:
        auth_views ([type]): [description]
    """
    template_name = 'login.html'

auction_site/auction/templates/auction/auction.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for obj in object_list %}
    <div class="col">
        <div class="card shadow-sm">
            {% if not obj.not_expired %}
                <h5>WINNER: {{obj.bids.all.last.user.email}}</h5>
            {% endif %}
            <img  class="bd-placeholder-img card-img-top" width="100%" height="225" src="{% if obj.image %}{{obj.image.url}}{% else %}No image{% endif %}" alt="No image">
            <div class="card-body">
            <h5 class="card-title">{{obj.title}}</h5>
            <p class="card-text">{{obj.description}}</p>
            <p>Current bid: {{obj.min_bid}}</p>
            <p>Total bids: {{obj.bids.all.count}}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'auction:auction-details' obj.id %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                    {% if obj.not_expired %}
                        <a href="{% url 'auction:raise-bid' obj.id %}" type="button" class="btn btn-sm btn-outline-secondary">New Bid</a>
                    {% endif %}
                </div>
                <small class="text-muted">Ends in:{{obj.time_ending|naturaltime }}</small>
            </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

auction_site/auction/templates/auction/auction_detail.html
{% extends 'base.html' %}
{% block content%}
<p>Title: {{object.title}}</p>
<p>Description: {{object.description}}</p>
<p>Current bid: {{object.min_bid}}</p>

<p>Starting Time: {{object.time_starting}}</p>
<p>End Time: {{object.time_ending}}</p>
<hr>
<h5 class="text-center">Total Bids</h5>
<table class="table">
    <thead class="thead-dark">
        <tr>
        <th scope="col">Email</th>
        <th scope="col">Bid time</th>
        </tr>
    </thead>

    <tbody>
    {% for item in object.bids.all %}
        <tr>
            <td>{{item.user.email}}</td>
            <td>{{item.bid_time}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<hr>
{% endblock %}

auction_site/auction/templates/auction/auction_form.html
{% extends 'base.html' %}

{% block content %}
<h3>Add your auction item</h3>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock content %}

auction_site/auction/templates/base.html
<!doctype html>
{% load static%}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Auction Away</title>

    <!-- Bootstrap core CSS -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


  </head>
  <body>

<header>
    {% include 'navbar.html'%}
</header>

<main>

  <div class="album py-5 bg-light">
    <div class="container">
    {% block content %}
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
          {% endfor %}
      </ul>
      {% endif %}
    {% endblock content %}

    </div>
  </div>

</main>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


  </body>
</html>

auction_site/auction/templates/navbar.html
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="{% url 'auction:auction-list'%}" class="navbar-brand d-flex align-items-center">
            <strong>Auction Away</strong>
        </a>
        <a class='btn btn-light' href="{% url 'auction:auction-create'%}"> Add new auction</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            {% comment %} <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li> {% endcomment %}
            <li class="nav-item">
                <a class="nav-link" href="">
                    {% if request.user.is_authenticated %}
                        Welcome '{{ request.user.email }}'
                        <a href="{%url 'users:logout'%}"> logout</a>
                    {% else %}
                        <a href="{% url django.contrib.auth.login %}">Login</a>
                    {% endif %}
                </a>
            </li>
            <li class="nav_item">

            </li>
            </ul>
        </div>
    </div>
</div>

auction_site/users/templates/login.html
<!DOCTYPE html>
<html>

    <head>
        <title>Login</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
            integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


        <style>
            body,
            html {
                margin: 0;
                padding: 0;
                height: 100%;
                background: #7abecc !important;
            }

            .user_card {
                width: 350px;
                margin-top: auto;
                margin-bottom: auto;
                background: #74cfbf;
                position: relative;
                display: flex;
                justify-content: center;
                flex-direction: column;
                padding: 10px;
                box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                border-radius: 5px;

            }

            .form_container {
                margin-top: 20px;
            }

            #form-title {
                color: #fff;

            }

            .login_btn {
                width: 100%;
                background: #33ccff !important;
                color: white !important;
            }

            .login_btn:focus {
                box-shadow: none !important;
                outline: 0px !important;
            }

            .login_container {
                padding: 0 2rem;
            }

            .input-group-text {
                background: #f7ba5b !important;
                color: white !important;
                border: 0 !important;
                border-radius: 0.25rem 0 0 0.25rem !important;
            }

            .input_user,
            .input_pass:focus {
                box-shadow: none !important;
                outline: 0px !important;
            }

            #messages {
                background-color: grey;
                color: #fff;
                padding: 10px;
                margin-top: 10px;
            }

        </style>

    </head>


    <body>
        <div class="container h-100">
            <div class="d-flex justify-content-center h-100">
                <div class="user_card">

                    <div class="d-flex justify-content-center">

                        <h3 id="form-title">LOGIN</h3>
                    </div>
                    <div class="d-flex justify-content-center form_container">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                {% comment %} <input type="email" name="email" placeholder="Email..." class="form-control"> {% endcomment %}
                                {{form.username}}
                            </div>
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                                </div>
                                {{form.password}}
                            </div>

                            <div class="d-flex justify-content-center mt-3 login_container">
                                <input class="btn login_btn" type="submit" value="Login">
                            </div>
                        </form>
                    </div>
                    {{form.errors}}

                    <div class="mt-4">
                        <div class="d-flex justify-content-center links">
                            Don't have an account? <a href="{% url 'users:signup' %}" class="ml-2">Sign Up</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </body>

</html>

<form action="" method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit">sdsd</button>
</form>

auction_site/users/templates/signup.html
{{ form.email.verbose_name }}
<!DOCTYPE html>
<html>

    <head>
        <title>Register</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
            integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

        <style>
            body,
            html {
                margin: 0;
                padding: 0;
                height: 100%;
                background: #7abecc !important;
            }

            .user_card {
                width: 350px;
                margin-top: auto;
                margin-bottom: auto;
                background: #74cfbf;
                position: relative;
                display: flex;
                justify-content: center;
                flex-direction: column;
                padding: 10px;
                box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                border-radius: 5px;

            }

            .form_container {
                margin-top: 20px;
            }

            #form-title {
                color: #fff;
            }

            .login_btn {
                width: 100%;
                background: #33ccff !important;
                color: white !important;
            }

            .login_btn:focus {
                box-shadow: none !important;
                outline: 0px !important;
            }

            .login_container {
                padding: 0 2rem;
            }

            .input-group-text {
                background: #f7ba5b !important;
                color: white !important;
                border: 0 !important;
                border-radius: 0.25rem 0 0 0.25rem !important;
            }

            .input_user,
            .input_pass:focus {
                box-shadow: none !important;
                outline: 0px !important;
            }

        </style>

    </head>

    <body>
        <div class="container h-100">
            <div class="d-flex justify-content-center h-100">
                <div class="user_card">
                    <div class="d-flex justify-content-center">
                        <h3 id="form-title">REGISTER ACCOUNT</h3>
                    </div>
                    <div class="d-flex justify-content-center form_container">

                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                                </div>
                                {{ form.email }}
                            </div>

                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                                </div>
                                {{ form.password1 }}
                            </div>
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                                </div>
                                {{ form.password2 }}
                            </div>
                            <div class="d-flex justify-content-center mt-3 login_container">
                                <input class="btn login_btn" type="submit" value="Register Account">
                            </div>
                        </form>
                    </div>
                    {{ form.errors }}
                    <div class="mt-4">
                        <div class="d-flex justify-content-center links">
                            Already have an account? <a href="{% url 'users:login' %}" class="ml-2">Login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

</html>